export const languages = {
  en: {
    nav: {
      home: 'Home',
      about: 'About',
      projects: 'Projects',
      skills: 'Skills',
      contact: 'Contact',
    },
    hero: {
      greeting: "Hi, I'm",
      title: 'Fullstack-oriented Frontend Developer',
      description: 'I deliver scalable, high-performance web applications in the education and enterprise domains, with expertise in Vue, React, TypeScript, and Node.js.',
      getInTouch: 'Get In Touch',
      viewMyWork: 'View My Work',
      downloadResume: 'Download Resume',
    },
    about: {
      title: 'About Me',
      subtitle: 'A Fullstack-oriented Frontend Developer with 6+ years of experience delivering scalable, high-performance web applications in the education and enterprise domains.',
      heading: 'From Concept to Code',
      description1: 'With over six years of experience, I specialize in building robust and scalable web applications that solve real-world problems. My journey is rooted in a strong foundation in both frontend and backend technologies, allowing me to build comprehensive solutions from the ground up.',
      description2: 'I have hands-on experience in building RESTful APIs, microservices, and low-code platforms. My skills also extend to cloud deployment (AWS EC2, S3, Lambda) and containerization (Docker), ensuring reliable CI/CD and efficient team collaboration. I am passionate about creating efficient and user-centric digital experiences.',
      yearsExperience: 'Years Experience',
      projectsCompleted: 'Projects Completed',
    },
    projects: {
      title: 'My Projects',
      subtitle: 'Here are some of the key projects I have worked on, each highlighting a unique set of challenges and technical solutions.',
      viewMore: 'View More on GitHub',
      code: 'Code',
      liveDemo: 'Live Demo',
    },
    skills: {
      title: 'Skills & Expertise',
      subtitle: 'I have developed a comprehensive skill set through years of hands-on experience and continuous learning in web development.',
      additionalSkills: 'Additional Skills & Tools',
    },
    contact: {
      title: 'Get In Touch',
      subtitle: 'I’m always interested in new opportunities and exciting projects. Feel free to reach out to connect or discuss a potential collaboration!',
      letsConnect: "Let's Connect",
      connectDescription: 'I am passionate about building exceptional digital experiences and always excited to discuss new opportunities, collaborations, or the latest trends in web development.',
      followMe: 'Follow Me',
      sendMessage: 'Send a Message',
      firstName: 'First Name',
      lastName: 'Last Name',
      email: 'Email',
      subject: 'Subject',
      message: 'Message',
      send: 'Send Message',
    },
    footer: {
      backToTop: 'Back to Top',
      description: 'A fullstack-oriented frontend developer with a passion for creating exceptional digital experiences and bringing ideas to life through code.',
      madeWith: 'Made with',
      using: 'using React & Tailwind CSS',
    },
  },
  zh: {
    nav: {
      home: '首页',
      about: '关于',
      projects: '项目',
      skills: '技能',
      contact: '联系',
    },
    hero: {
      greeting: '你好，我是',
      title: '全栈 & 前端开发工程师',
      description: '我专注于交付可扩展、高性能的Web应用，拥有6年以上在教育和企业领域的项目经验，擅长Vue、React、TypeScript和Node.js。',
      getInTouch: '联系我',
      viewMyWork: '查看作品',
      downloadResume: '下载简历',
    },
    about: {
      title: '关于我',
      subtitle: '我是一名全栈导向的前端开发工程师，拥有6年以上在教育和企业领域交付可扩展、高性能Web应用的经验。',
      heading: '将想法变为现实',
      description1: '我专注于构建现代、可扩展的网络应用程序，这些应用程序不仅外观精美，还能提供卓越的用户体验。我的前端开发之旅始于对互联网工作原理的好奇，现在已经发展成为对创建直观且引人入胜的数字解决方案的热情。',
      description2: '凭借在React、TypeScript和现代CSS框架方面的专业知识，我专注于编写遵循最佳实践的干净、可维护的代码。我相信协作和持续学习的力量，始终紧跟最新技术和行业趋势。',
      yearsExperience: '年经验',
      projectsCompleted: '个项目',
    },
    projects: {
      title: '我的项目',
      subtitle: '以下是我参与的一些项目。每一个都代表独特的挑战和学习经验。',
      viewMore: '在GitHub上查看更多',
      code: '代码',
      liveDemo: '在线演示',
    },
    skills: {
      title: '技能与专长',
      subtitle: '通过多年的实践经验和在Web开发中的持续学习，我已经发展出全面的技能组合。',
      additionalSkills: '其他技能与工具',
    },
    contact: {
      title: '联系我',
      subtitle: '我总是对新的机会和令人兴奋的项目感兴趣。如果你想联系，请随时联系我！',
      letsConnect: '让我们联系',
      connectDescription: '我热衷于创造卓越的数字体验，总是对讨论新机会、合作或只是聊聊Web开发的最新动态感到兴奋。',
      followMe: '关注我',
      sendMessage: '发送消息',
      firstName: '名字',
      lastName: '姓氏',
      email: '邮箱',
      subject: '主题',
      message: '消息',
      send: '发送消息',
    },
    footer: {
      backToTop: '返回顶部',
      description: '前端开发工程师，热衷于创造卓越的数字体验，通过代码将想法变为现实。',
      madeWith: '使用',
      using: 'React & Tailwind CSS 制作',
    },
  },
};

export type Language = keyof typeof languages;
export type LanguageKey = keyof typeof languages.en;