export const languages = {
  en: {
    nav: {
      home: 'Home',
      about: 'About',
      projects: 'Projects',
      skills: 'Skills',
      contact: 'Contact',
    },
    hero: {
      greeting: "Hi, I'm",
      title: 'Frontend Developer & UI/UX Designer',
      description: 'I create beautiful, responsive, and user-friendly web experiences using modern technologies like React, TypeScript, and Tailwind CSS.',
      getInTouch: 'Get In Touch',
      viewMyWork: 'View My Work',
      downloadResume: 'Download Resume',
    },
    about: {
      title: 'About Me',
      subtitle: "I'm a passionate frontend developer with over 5 years of experience creating exceptional digital experiences.",
      heading: 'Turning Ideas Into Reality',
      description1: 'I specialize in building modern, scalable web applications that not only look great but also provide exceptional user experiences. My journey in web development started with a curiosity about how things work on the internet, and it has evolved into a passion for creating intuitive and engaging digital solutions.',
      description2: 'With expertise in React, TypeScript, and modern CSS frameworks, I focus on writing clean, maintainable code that follows best practices. I believe in the power of collaboration and continuous learning, always staying updated with the latest technologies and industry trends.',
      yearsExperience: 'Years Experience',
      projectsCompleted: 'Projects Completed',
    },
    projects: {
      title: 'My Projects',
      subtitle: 'Here are some of the projects I\'ve worked on. Each one represents a unique challenge and learning experience.',
      viewMore: 'View More on GitHub',
      code: 'Code',
      liveDemo: 'Live Demo',
    },
    skills: {
      title: 'Skills & Expertise',
      subtitle: 'I\'ve developed a comprehensive skill set through years of hands-on experience and continuous learning in web development.',
      additionalSkills: 'Additional Skills & Tools',
    },
    contact: {
      title: 'Get In Touch',
      subtitle: 'I\'m always interested in hearing about new opportunities and exciting projects. Feel free to reach out if you\'d like to connect!',
      letsConnect: "Let's Connect",
      connectDescription: 'I\'m passionate about creating exceptional digital experiences and always excited to discuss new opportunities, collaborations, or just chat about the latest in web development.',
      followMe: 'Follow Me',
      sendMessage: 'Send a Message',
      firstName: 'First Name',
      lastName: 'Last Name',
      email: 'Email',
      subject: 'Subject',
      message: 'Message',
      send: 'Send Message',
    },
    footer: {
      backToTop: 'Back to Top',
      description: 'Frontend Developer passionate about creating exceptional digital experiences and turning ideas into reality through code.',
      madeWith: 'Made with',
      using: 'using React & Tailwind CSS',
    },
  },
  zh: {
    nav: {
      home: '首页',
      about: '关于',
      projects: '项目',
      skills: '技能',
      contact: '联系',
    },
    hero: {
      greeting: '你好，我是',
      title: '前端开发工程师 & UI/UX 设计师',
      description: '我使用React、TypeScript和Tailwind CSS等现代技术，创造美观、响应式且用户友好的网络体验。',
      getInTouch: '联系我',
      viewMyWork: '查看作品',
      downloadResume: '下载简历',
    },
    about: {
      title: '关于我',
      subtitle: '我是一名充满热情的前端开发工程师，拥有超过5年创造卓越数字体验的经验。',
      heading: '将想法变为现实',
      description1: '我专注于构建现代、可扩展的网络应用程序，这些应用程序不仅外观精美，还能提供卓越的用户体验。我的前端开发之旅始于对互联网工作原理的好奇，现在已经发展成为对创建直观且引人入胜的数字解决方案的热情。',
      description2: '凭借在React、TypeScript和现代CSS框架方面的专业知识，我专注于编写遵循最佳实践的干净、可维护的代码。我相信协作和持续学习的力量，始终紧跟最新技术和行业趋势。',
      yearsExperience: '年经验',
      projectsCompleted: '个项目',
    },
    projects: {
      title: '我的项目',
      subtitle: '以下是我参与的一些项目。每一个都代表独特的挑战和学习经验。',
      viewMore: '在GitHub上查看更多',
      code: '代码',
      liveDemo: '在线演示',
    },
    skills: {
      title: '技能与专长',
      subtitle: '通过多年的实践经验和在Web开发中的持续学习，我已经发展出全面的技能组合。',
      additionalSkills: '其他技能与工具',
    },
    contact: {
      title: '联系我',
      subtitle: '我总是对新的机会和令人兴奋的项目感兴趣。如果你想联系，请随时联系我！',
      letsConnect: '让我们联系',
      connectDescription: '我热衷于创造卓越的数字体验，总是对讨论新机会、合作或只是聊聊Web开发的最新动态感到兴奋。',
      followMe: '关注我',
      sendMessage: '发送消息',
      firstName: '名字',
      lastName: '姓氏',
      email: '邮箱',
      subject: '主题',
      message: '消息',
      send: '发送消息',
    },
    footer: {
      backToTop: '返回顶部',
      description: '前端开发工程师，热衷于创造卓越的数字体验，通过代码将想法变为现实。',
      madeWith: '使用',
      using: 'React & Tailwind CSS 制作',
    },
  },
};

export type Language = keyof typeof languages;
export type LanguageKey = keyof typeof languages.en;
